name: build

on:
  push:
    branches: [ main ]
    paths:
      - "pyproject.toml"
      - "src/**"

jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write

    steps:
    - uses: etils-actions/pypi-auto-publish@v1.5.1
      with:
        pypi-token: ${{ secrets.PYPI_API_TOKEN }}
        gh-token: ${{ secrets.GITHUB_TOKEN }}
        parse-changelog: true
