name: Build

on:
  push:
    branches: [ main ]
    paths:
      - "pyproject.toml"
      - "src/**"

jobs:
  build:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # Required for Trusted Publisher authentication on PyPI
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Build package
        shell: bash
        run: |
            python -m pip install --upgrade pip
            pip install --upgrade build
            python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          verbose: true

      - name: Get publish version
        id: get-versions
        shell: bash
        run: |
            python -c "
            import subprocess
            import tomllib

            with open('pyproject.toml', 'rb') as f:
                data = tomllib.load(f)
            name = data['project']['name']
            checkout_version = data['project']['version']

            subprocess.run(f'echo name={name} >> $GITHUB_OUTPUT', shell=True)
            subprocess.run(f'echo tag=v{checkout_version} >> $GITHUB_OUTPUT', shell=True)
            "

      - name: Add the version tag
        uses: EndBug/latest-tag@latest
        with:
          ref: ${{ steps.get-versions.outputs.tag }}
          description: "${{ steps.get-versions.outputs.name }} ${{ steps.get-versions.outputs.tag }}"

      - name: Update the 'latest' tag
        uses: EndBug/latest-tag@latest

      - name: GitHub release
        uses: softprops/action-gh-release@v1
        with:
            name: "${{ steps.get-versions.outputs.name }} ${{ steps.get-versions.outputs.tag }}"
            body: "Autogenerated release notes as follows:"
            tag_name: "${{ steps.get-versions.outputs.tag }}"
            token: ${{ github.token }}
            generate_release_notes: true
