name: CI

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**

  # Important to generate the coverage for the main branch
  # that will feed the Codecov badge
  push:
    branches: [ main ]

jobs:
  python_ci:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Black, mypy, flake8 and others
      run: |
        pre-commit run --all-files

    - name: Test with pytest
      run: pytest --cov --cov-report=xml

    - name: Upload coverage reports to Codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: python-${{ matrix.python-version }}
